### PR TITLE
fix: base permission __eq__

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-:-NqhnVB28eDPk7PgQlo_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86)* status: all files reviewed, 7 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/tests/model_view_set.py` line 618 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-Nqldv-a2B6dRpWMdGHT:-Nqldv-a2B6dRpWMdGHU:b-7vnuuj) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L618)):*
> ```Python
>         Args:
>             email: The user's email address.
>             password: The user's password.
> ```

What is our convention for args again - do we decide that if the arg is self-explanatory we don't include it in the docstring? Cos in this case, I'd say this isn't needed.



_Code quote:_
```Python
        Args:
            email: The user's email address.
            password: The user's password.
```
___
*[`codeforlife/tests/model_view_set.py` line 695 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-Nqle5c_2Uz1cjqkv9Yu:-Nqle5c_2Uz1cjqkv9Yv:b-gp6bji) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L695)):*
> ```Python
>             class_id: The ID of the class the student belongs to.
>             username: The user's username.
>             password: The user's password.
> ```

Maybe same for this



_Code quote:_
```Python
            class_id: The ID of the class the student belongs to.
            username: The user's username.
            password: The user's password.
```
___
*[`codeforlife/tests/model_view_set.py` line 726 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqleCbT2t6t7IAdc1wr:-NqleCbUCX5dF2Wdpc_G:bxttjap) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L726)):*
> ```Python
>             password: The user's password.
>         """
> ```

No space after docstring
___
*[`codeforlife/tests/model_view_set.py` line 727 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqleKsD1xHCOLk9vye7:-NqleKsD1xHCOLk9vye8:bru4i87) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L727)):*
> ```Python
>         """
> 
>         if isinstance(user, TeacherUser):
> ```

Question about TeacherUser - do we need it? Teacher can only be 1 of 4 cases as shown below, SchoolTeacher, NonSchoolTeacher, AdminSchoolTeacher and NonAdminSchoolTeacher. So, is TeacherUser needed? What setup does a TeacherUser have, surely it falls under one of the other 4 proxies right?
___
*[`codeforlife/user/permissions/is_teacher.py` line 32 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqlfGaO1W23SjXtjgS4:-NqlfGaO1W23SjXtjgS5:bndjiq0) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/user/permissions/is_teacher.py#L32)):*
> ```Python
>         super().__init__()
> 
>         if is_admin is True or in_class is True:
> ```

No need to do `is True` for these here
___
*[`codeforlife/user/views/klass.py` line 22 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqlhG-9D8ZrYHrDG6Es:-NqlhG-9D8ZrYHrDG6Et:b-l6rsl1) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/user/views/klass.py#L22)):*
> ```Python
>         # Only school-teachers can list classes.
>         if self.action == "list":
>             return [IsTeacher(in_school=True)]
> ```

Actually, only school admins OR standard school teachers in a class can list classes, right? IE, school teachers without a class can't list them. So do we need to pass in `in_class=True?` for non-admins?
___
*[`codeforlife/user/views/klass.py` line 24 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqlhLFI1IkrOp3hck1X:-NqlhLFI1IkrOp3hck1Y:bfrumwx) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/user/views/klass.py#L24)):*
> ```Python
>             return [IsTeacher(in_school=True)]
> 
>         return [OR(IsStudent(), IsTeacher(in_school=True))]
> ```

Same here, standard school teachers that aren't in a class can't retrieve a class.

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86)* status: 17 of 21 files reviewed, 7 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/tests/model_view_set.py` line 618 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-Nqldv-a2B6dRpWMdGHT:-Nqm1BbtEuJd7Wxg3ROs:btmw75b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L618)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

What is our convention for args again - do we decide that if the arg is self-explanatory we don't include it in the docstring? Cos in this case, I'd say this isn't needed.
</blockquote></details>

Last we discussed, we agreed that we would either add a function docstring if an explanation was needed or omit the string entirely if it's part of the framework/super class.

Happy to adjust our strategy on this though.

We never discussed omitting parts of function's docstring.
___
*[`codeforlife/tests/model_view_set.py` line 695 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-Nqle5c_2Uz1cjqkv9Yu:-Nqm1y9h4nWTsJ4Am5YC:byr4ffv) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L695)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Maybe same for this
</blockquote></details>

see above
___
*[`codeforlife/tests/model_view_set.py` line 726 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqleCbT2t6t7IAdc1wr:-Nqm2pQcCJURveX5iZ_k:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L726)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

No space after docstring
</blockquote></details>

Done.
___
*[`codeforlife/tests/model_view_set.py` line 727 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqleKsD1xHCOLk9vye7:-Nqm2soWDRtcZHqIwbFD:bevfb4y) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L727)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Question about TeacherUser - do we need it? Teacher can only be 1 of 4 cases as shown below, SchoolTeacher, NonSchoolTeacher, AdminSchoolTeacher and NonAdminSchoolTeacher. So, is TeacherUser needed? What setup does a TeacherUser have, surely it falls under one of the other 4 proxies right?
</blockquote></details>

you are right in that a teacher-user is one of the 4 teacher type (school, non-school, admin, non-admin). However, we still need TeacherUser for when you want to filter to any teacher type. Say I had a test case where I needed a teacher of any type, the I would use TeacherUser. I do have some test cases already where this is the case. For example, testing a teacher's OTP auth factor. It's irrelevant what type of teacher. 
___
*[`codeforlife/user/permissions/is_teacher.py` line 32 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqlfGaO1W23SjXtjgS4:-Nqm6_NODfZ3L-v_CwCF:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/user/permissions/is_teacher.py#L32)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

No need to do `is True` for these here
</blockquote></details>

Done.
___
*[`codeforlife/user/views/klass.py` line 22 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqlhG-9D8ZrYHrDG6Es:-Nqm7_MADjPL1vq7ffs6:b-us73mr) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/user/views/klass.py#L22)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Actually, only school admins OR standard school teachers in a class can list classes, right? IE, school teachers without a class can't list them. So do we need to pass in `in_class=True?` for non-admins?
</blockquote></details>

Done. good catch.
___
*[`codeforlife/user/views/klass.py` line 24 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-NqlhLFI1IkrOp3hck1X:-Nqm7bz_DYMh0MqGTNMX:b-us73mr) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/user/views/klass.py#L24)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same here, standard school teachers that aren't in a class can't retrieve a class.
</blockquote></details>

Done. good catch.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`codeforlife/tests/model_view_set.py` line 618 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-Nqldv-a2B6dRpWMdGHT:-NqmH2UmAelKkur5dVz1:bkfq7sn) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L618)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Last we discussed, we agreed that we would either add a function docstring if an explanation was needed or omit the string entirely if it's part of the framework/super class.

Happy to adjust our strategy on this though.

We never discussed omitting parts of function's docstring.
</blockquote></details>

I don't really mind either way, but I believe when I was working on the invitation task we decided not to include args like `pk` and `token` because they were too obvious. I don't mind though, happy to include all args as a rule if we want.

It's probably easier to just do that to be fair. Let's include all args then, agreed?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`codeforlife/tests/model_view_set.py` line 618 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86#-Nqldv-a2B6dRpWMdGHT:-NqmIsDb8nJCfe6NLkEg:b9ccj4z) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/22dfe33ed8f3b85fb7e939e746b806cc12a4305d/codeforlife/tests/model_view_set.py#L618)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I don't really mind either way, but I believe when I was working on the invitation task we decided not to include args like `pk` and `token` because they were too obvious. I don't mind though, happy to include all args as a rule if we want.

It's probably easier to just do that to be fair. Let's include all args then, agreed?
</blockquote></details>

Yes, agreed. let's do that just to stay consistent.

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/86)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
