### PR TITLE
feat: update teacher

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/78)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/78#-:-NqCclpXCbLFhYDCoww5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`codeforlife/user/models/user.py` line 143 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/78#-NqCboZE8n3_0lVULhCI:-NqCboZE8n3_0lVULhCJ:bm0wn7g) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/958bb10b991c9fc83baa00a1368e6d0c5d40c3af/codeforlife/user/models/user.py#L143)):*
> ```Python
> 
> class AdminSchoolTeacherUser(User):
>     """A user that is an  admin-teacher in a school."""
> ```

double space

**Review by faucomte97 — CHANGES_REQUESTED** [review]
no

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/78#-:-NqCcr9LA6Z5vAARKfUQ:b32wsm)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/78)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`codeforlife/user/models/user.py` line 143 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/78#-NqCboZE8n3_0lVULhCI:-NqCd8vr5Rzf8dRuqDbT:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/958bb10b991c9fc83baa00a1368e6d0c5d40c3af/codeforlife/user/models/user.py#L143)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

double space
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/78)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
