### PR TITLE
fix: model view set test case

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/62)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/62)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`codeforlife/user/models/otp_bypass_token.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/62#-Np-ECZi2WpQBoTxkaM3:-Np-ECZjEcvzXOWkF2nk:b8g74k7) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/195f1d90a471951ad418ad1fe444a5ee2adb1ac2/codeforlife/user/models/otp_bypass_token.py#L15)):*
> ```Python
> class OtpBypassToken(models.Model):
>     length = 8
>     allowed_chars = "abcdefghijklmnopqrstuv"
> ```

Why? Why not all the letters?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/62)* status: 11 of 24 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`codeforlife/user/models/otp_bypass_token.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/62#-Np-ECZi2WpQBoTxkaM3:-Np-UL7SDv1fNOCITcPl:b-q6hu9q) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/195f1d90a471951ad418ad1fe444a5ee2adb1ac2/codeforlife/user/models/otp_bypass_token.py#L15)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why? Why not all the letters?
</blockquote></details>

My bad. Fixed.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/62)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/62#-:-Np-XN7oDC7x5e4K3cjV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
