### PR TITLE
fix: model view set test case

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60)* status: all files reviewed, 6 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/user/serializers/school.py` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol01xa4Gtlty23d4gZ:-Nol01xb70fpZ01Phon0:b-iealql) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/serializers/school.py#L29)):*
> ```Python
>             "id": instance.id,
>             "name": instance.name,
>             "country": str(instance.country),
> ```

Why do you stringify this?
___
*[`codeforlife/user/serializers/student.py` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol0dJM0PBYA4lk4CB8:-Nol0dJM0PBYA4lk4CB9:bofjinr) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/serializers/student.py#L27)):*
> ```Python
>             "id": instance.id,
>             "klass": instance.class_field.access_code,
>             "school": instance.class_field.teacher.school.pk,
> ```

`school` isn't listed in the `fields`, is this OK?
___
*[`codeforlife/user/serializers/user.py` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol18e5CiHVzo7kAapB:-Nol18e5CiHVzo7kAapC:b-fy2ceo) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/serializers/user.py#L31)):*
> ```Python
>             "teacher",
>             "id",
>             "password",
> ```

I thought the issue with `__all__` was that it included fields like `password` yet it's still here?
___
*[`codeforlife/user/tests/views/test_user.py` line 266 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol24Wc-85XSZ2CYu83:-Nol24Wc-85XSZ2CYu84:b2wjwoh) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/tests/views/test_user.py#L266)):*
> ```Python
>         )
> 
>         self.client.retrieve(other_user, status.HTTP_404_NOT_FOUND)
> ```

Confused as to why a student can't retrieve their own teacher?
___
*[`codeforlife/user/tests/views/test_user.py` line 449 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol34wV5tRAGJRrIfOo:-Nol34wV5tRAGJRrIfOp:b1vih6g) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/tests/views/test_user.py#L449)):*
> ```Python
>     def test_list__teacher(self):
>         """
>         Teacher can list all the users in the same school.
> ```

Teacher should only be allowed to list all teachers in the same school & all students in their classes.
Only admin teachers can list all the users in the same school.
___
*[`codeforlife/user/tests/views/test_user.py` line 479 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol3CcZ8yfx-ekjYfw0:-Nol3CcZ8yfx-ekjYfw1:b-ifzfc4) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/tests/views/test_user.py#L479)):*
> ```Python
>     def test_list__student(self):
>         """
>         Student can list only themself.
> ```

Can't student list all users in their class? ie classmates + teacher?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60)* status: 20 of 22 files reviewed, 6 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/user/serializers/school.py` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol01xa4Gtlty23d4gZ:-Nol8kV_8gjYZgQ2Z1Df:b-o831u6) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/serializers/school.py#L29)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why do you stringify this?
</blockquote></details>

yes. otherwise JSON cannot serialize this object.
___
*[`codeforlife/user/serializers/student.py` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol0dJM0PBYA4lk4CB8:-Nol8vHj5pJMPRc0Ap42:b-dk3nb5) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/serializers/student.py#L27)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

`school` isn't listed in the `fields`, is this OK?
</blockquote></details>

no. it should be. fixed.
___
*[`codeforlife/user/serializers/user.py` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol18e5CiHVzo7kAapB:-Nol9H1N5E8VphGv-roN:bxz2z17) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/serializers/user.py#L31)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I thought the issue with `__all__` was that it included fields like `password` yet it's still here?
</blockquote></details>

password needs to be added in the fields so you can PATCH your password. however, down below in extra_kwargs I specify password is write_only=True (cannnot read) 
___
*[`codeforlife/user/tests/views/test_user.py` line 266 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol24Wc-85XSZ2CYu83:-Nol9i9n3186qIByRg5_:b-j51p4s) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/tests/views/test_user.py#L266)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Confused as to why a student can't retrieve their own teacher?
</blockquote></details>

I think it's just because no where in the app do we allow students to see their class' teacher. We can change this later if need be but I disallowed it for now as I'm trying to follow the principal of minimal privilege/access.
___
*[`codeforlife/user/tests/views/test_user.py` line 449 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol34wV5tRAGJRrIfOo:-NolAEsd5jzfT6L81L36:byw0qvd) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/tests/views/test_user.py#L449)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Teacher should only be allowed to list all teachers in the same school & all students in their classes.
Only admin teachers can list all the users in the same school.
</blockquote></details>

The test does check that. Just the test description was wrong
___
*[`codeforlife/user/tests/views/test_user.py` line 479 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-Nol3CcZ8yfx-ekjYfw0:-NolHsD_Eu-zX4KpmoCD:b-f2b3ua) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d6ad73c14bfdf79914dac58f9be70fe0c00628de/codeforlife/user/tests/views/test_user.py#L479)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Can't student list all users in their class? ie classmates + teacher?
</blockquote></details>

yes! fixed!

**Review by faucomte97 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60#-:-Nom-ioHCqvt8FvsdtWW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/60)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
