### PR TITLE
New data model permissions

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/user/permissions/is_teacher.py` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29#-NlibEPL8CqcFegpfRub:-NlibEPL8CqcFegpfRuc:b-x7o73i) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/5eac7fde349acf9076cd46b035a5147b28b278cc/codeforlife/user/permissions/is_teacher.py#L29)):*
> ```Python
>                 teacher. Else, check if the user is the specific teacher.
>             is_admin: If the teacher is an admin. If None, don't check if the
>                 teacher is an admin. Else, check if the teacher is (not) an
> ```

what do you mean "check if *not* an admin", isn't it the other way around?
___
*[`codeforlife/user/permissions/is_teacher.py` line 45 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29#-NlibOooAPeVMFTDTHOe:-NlibOooAPeVMFTDTHOf:b3619hk) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/5eac7fde349acf9076cd46b035a5147b28b278cc/codeforlife/user/permissions/is_teacher.py#L45)):*
> ```Python
>             and (
>                 self.is_admin is None
>                 or t.cast(Teacher, user.teacher).is_admin == self.is_admin
> ```

Does the code not recognise `user.teacher`, hence the casting? :confused: 
___
*[`codeforlife/user/views/user.py` line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29#-Nlicq5UAlzPdjGNvaeJ:-Nlicq5UAlzPdjGNvaeK:b-tk2nxe) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/5eac7fde349acf9076cd46b035a5147b28b278cc/codeforlife/user/views/user.py#L24)):*
> ```Python
>             return User.objects.none()
> 
>         if user.student:
> ```

Wanted to bring this up again actually. In other cases we've been using `user.student is not None` but here we're doing just `user.student`, for example. While I was advocating for the latter because it's simpler and easier to read, I remembered that they are not technically equivalent as Python will go through a series of checks if we don't specify `is (not) None`. If we think it's safe enough to leave it as it is though, we can see. Happy to discuss this further.

**Comment by SKairinos** [comment]
*[`codeforlife/user/views/user.py` line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29#-Nlicq5UAlzPdjGNvaeJ:-NlwHGqS1v9lZn-S8ui5:bpx44e9) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/5eac7fde349acf9076cd46b035a5147b28b278cc/codeforlife/user/views/user.py#L24)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Wanted to bring this up again actually. In other cases we've been using `user.student is not None` but here we're doing just `user.student`, for example. While I was advocating for the latter because it's simpler and easier to read, I remembered that they are not technically equivalent as Python will go through a series of checks if we don't specify `is (not) None`. If we think it's safe enough to leave it as it is though, we can see. Happy to discuss this further.
</blockquote></details>

I agree with you. Let's make it explicit with "is not None" to be safe.

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29)* status: 38 of 39 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/user/permissions/is_teacher.py` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29#-NlibEPL8CqcFegpfRub:-NlwGPCl3SPjzYwDCoHh:bsh2oi2) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/5eac7fde349acf9076cd46b035a5147b28b278cc/codeforlife/user/permissions/is_teacher.py#L29)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

what do you mean "check if *not* an admin", isn't it the other way around?
</blockquote></details>

if is_admin=None, it will not check admin status.
if is_admin=True, it will check that the teacher is an admin
if is_admin=False, it will check that the teacher is not an admin.
___
*[`codeforlife/user/permissions/is_teacher.py` line 45 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29#-NlibOooAPeVMFTDTHOe:-NlwGeIH3mFLHm0iZQHl:b-pgwl0g) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/5eac7fde349acf9076cd46b035a5147b28b278cc/codeforlife/user/permissions/is_teacher.py#L45)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Does the code not recognise `user.teacher`, hence the casting? :confused:
</blockquote></details>

yes, exactly. Normally, teacher is None or instance of Teacher(). However, mypy does not know that teacher is not None at this point in the if check because mypy is ignorant to Django's internal workings. But we know it will not be none so I cast it so it knows it's an instance of Teacher() and not None.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29#-:-NlwV4bd08O6UtO9vAO3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

___
*[`codeforlife/user/permissions/is_teacher.py` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/29#-NlibEPL8CqcFegpfRub:-NlwUUjS0sDFaBk0n65M:b-qi6v81) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/5eac7fde349acf9076cd46b035a5147b28b278cc/codeforlife/user/permissions/is_teacher.py#L29)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

if is_admin=None, it will not check admin status.
if is_admin=True, it will check that the teacher is an admin
if is_admin=False, it will check that the teacher is not an admin.
</blockquote></details>

I see, so that (not) is a optional not in the sentence based on whether it's True or False. OK

**Pull request merged**
