### PR TITLE
fix: polish tests

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114#-:-Nw7HOuP5A0GIWhPbvrf:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`codecov.yml` line 6 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114#-Nw7DNSjEMjeref5C5MG:-Nw7DNSjEMjeref5C5MH:b-2x4wtp) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/7cf61cac74a19c2334c73fa41e6509afb520cd13/codecov.yml#L6)):*
> ```YAML
>   range: 90...90
>   status:
>     patch:
> ```

Following from what Duncan said in the sprint review meeting, should we bring a rule for `patch` back? To ensure some amount of the added code is tested? But then again, if we just ensure that the overall coverage doesn't decrease, that's also fine (sorry kinda thinking as I type).

Basically, I think the golden rule could be that *the overall coverage never goes down*. Regardless of how much code was actually covered in the PR itself. Probably easier said than done though.
___
*[`codecov.yml` line 9 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114#-Nw7CnHw2y7YLDySA4ua:-Nw7CnHx7-eZ7PxMYe-l:b-9rjioy) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c976486a02b1850b7ae15d05e01a7207d054cd6/codecov.yml#L9)):*
> ```YAML
>       default:
>         target: 90%
>         threshold: 0%
> ```

Do we need this mentioned at all or is the default value something other than 0? I couldn't find a default value mentioned in the docs.
___
*[`codeforlife/user/views/klass_test.py` line 87 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114#-Nw7EWG302NgBupcwbRM:-Nw7EWG302NgBupcwbRN:bwmybcu) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c976486a02b1850b7ae15d05e01a7207d054cd6/codeforlife/user/views/klass_test.py#L87)):*
> ```Python
> 
>         self.assert_get_queryset(
>             values=user.teacher.classes,
> ```

(Non-blocking comment):

This test has the exact same code as the previous one bar the user getter.
I get it's because in both cases we're using the `classes` prop which returns either the teacher's class if non-admin or all classes in the school if admin.

This is my question: since we're using the same prop in both tests, in this actually an indication that we should just be testing the `classes` prop in a model test instead to ensure it returns what we expect, instead of using it in both these model viewset tests? Or, at the end of the day, is it the same thing?

**Review by faucomte97 — CHANGES_REQUESTED** [review]
not lgtm lols

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114#-:-Nw7HSae4EFGdEUQ9mUU:by27dtw)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`codecov.yml` line 6 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114#-Nw7DNSjEMjeref5C5MG:-Nw9ZIXP3imA7PgnYnJO:b-wz15x9) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/7cf61cac74a19c2334c73fa41e6509afb520cd13/codecov.yml#L6)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Following from what Duncan said in the sprint review meeting, should we bring a rule for `patch` back? To ensure some amount of the added code is tested? But then again, if we just ensure that the overall coverage doesn't decrease, that's also fine (sorry kinda thinking as I type).

Basically, I think the golden rule could be that *the overall coverage never goes down*. Regardless of how much code was actually covered in the PR itself. Probably easier said than done though.
</blockquote></details>

I agree. I think we should make it so that the min coverage is 90 and that the coverage never goes down. I don't think we need the patch status check.
___
*[`codecov.yml` line 9 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114#-Nw7CnHw2y7YLDySA4ua:-Nw9ZaaJEM4LYdoD3fPh:bfwj7qr) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c976486a02b1850b7ae15d05e01a7207d054cd6/codecov.yml#L9)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need this mentioned at all or is the default value something other than 0? I couldn't find a default value mentioned in the docs.
</blockquote></details>

Setting this to 0 will means that coverage is allowed to go down by 0%. In other words, the coverage is not allowed to go down. The default value for this null, meaning the coverage can go down by any amount.
___
*[`codeforlife/user/views/klass_test.py` line 87 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114#-Nw7EWG302NgBupcwbRM:-Nw9_9kiCkqpCJbQVuQw:b-lyepg0) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c976486a02b1850b7ae15d05e01a7207d054cd6/codeforlife/user/views/klass_test.py#L87)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

(Non-blocking comment):

This test has the exact same code as the previous one bar the user getter.
I get it's because in both cases we're using the `classes` prop which returns either the teacher's class if non-admin or all classes in the school if admin.

This is my question: since we're using the same prop in both tests, in this actually an indication that we should just be testing the `classes` prop in a model test instead to ensure it returns what we expect, instead of using it in both these model viewset tests? Or, at the end of the day, is it the same thing?
</blockquote></details>

I think the correct answer is we should test both. We should test that:
1. The model property ".classes" returns the correct queryset
2. The model view set callback "get_queryset()" returns the correct queryset.

I understand your point that these are returning the same queryset so can we not just test one. However, while we know that these two queryset *should* be the same, we need test that they actually *are* the same and that something hasn't broken the queryset. This is especially important for future proofing - if any dev changes this code, these tests should assert that the queryset did not break.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/114#-:-NwB_Ksm5jHo4v9WHgAF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
