### PR TITLE
fix: alter the react endpoint and remove not found for /api/ endpoint

### PR DESCRIPTION
**Pull request by KamilPawel**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/14)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/14)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`codeforlife/urls.py` line 51 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/14#-NfkIv9_6k_PgeykvMDa:-NfkIv9_6k_PgeykvMDb:bjpeje7) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/f94f0c935ac660cd3afa7ada719a790322339389/codeforlife/urls.py#L51)):*
> ```Python
>         ),
>         re_path(
>             r"^(?!.*api/).*",
> ```

should be r"^(?!api/).*"
it must not start with "api/"

**Review by SKairinos — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/14)* status: all files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

**Review by SKairinos — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/14#-:-NfkKpCP7DCuO4YaKAsu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

**Review by KamilPawel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/14#-:-NfkM7Hc1sfEQF1ZCY3R:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`codeforlife/urls.py` line 51 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/14#-NfkIv9_6k_PgeykvMDa:-NfkM6XR63FDZABF86lO:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/f94f0c935ac660cd3afa7ada719a790322339389/codeforlife/urls.py#L51)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should be r"^(?!api/).*"
it must not start with "api/"
</blockquote></details>

Done.

**Review by SKairinos — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
