### PR TITLE
fix: register teacher

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`codeforlife/user/models/user.py` line 194 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104#-Ntpi1EyDXw2TxViaWeC:-Ntpi1EyDXw2TxViaWeD:bqvauxf) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/eb61ebc2aa46007d2485fe39c09feae19f783e5b/codeforlife/user/models/user.py#L194)):*
> ```Python
>             is_admin=is_admin,
>         )
> ```

At this point, in the current system we do this:

`TotalActivity.objects.update(teacher\_registrations\=F("teacher\_registrations") + 1)`

Do we want to keep these data-related lines of code wherever we have them, until we have completely transitioned to the new data strategy?

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/user/models/teacher.py` line 99 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104#-NtpliO40RvsGnX4Adgi:-NtpliO40RvsGnX4Adgj:bgrapyx) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/eb61ebc2aa46007d2485fe39c09feae19f783e5b/codeforlife/user/models/teacher.py#L99)):*
> ```Python
>         return (
>             not self.__class__.objects.filter(school=self.school, is_admin=True)
>             .exclude(pk=self.pk)
> ```

Double-checking: what happens here if you call `is_last_admin` on a non-admin teacher?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/user/models/teacher.py` line 99 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104#-NtpliO40RvsGnX4Adgi:-NtpvElu6oeBKaVR4IMV:bf14rmp) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/eb61ebc2aa46007d2485fe39c09feae19f783e5b/codeforlife/user/models/teacher.py#L99)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

You can't. See the AdminSchoolTeacher.Manager class. The queryset only includes admin teachers.
</blockquote></details>

In fact, I don't even the is_admin=True filter here since it's already filtered to that set

**Comment by SKairinos** [comment]
*[`codeforlife/user/models/teacher.py` line 99 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104#-NtpliO40RvsGnX4Adgi:-Ntpw9G91Z2rEUKMQShN:buj8cw0) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/eb61ebc2aa46007d2485fe39c09feae19f783e5b/codeforlife/user/models/teacher.py#L99)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

In fact, I don't even the is_admin=True filter here since it's already filtered to that set
</blockquote></details>

Also, this property is only on the AdminSchoolTeacher class

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`codeforlife/user/models/user.py` line 194 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104#-Ntpi1EyDXw2TxViaWeC:-NtqKVsc65zRv3fxROTC:bvhgl8n) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/eb61ebc2aa46007d2485fe39c09feae19f783e5b/codeforlife/user/models/user.py#L194)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

yes, we should keep them for now TBH. However, I'm confused as to why we don't just count the number of teacher objects?
</blockquote></details>

Because unfortunately they're not the same, since we deleted some users with our cron jobs for a few days before deciding we wanted to anonymise them instead - so we're using the TotalActivity table to keep track of the actual total figures

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`codeforlife/user/models/user.py` line 194 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104#-Ntpi1EyDXw2TxViaWeC:-Ntq_ZbJ8IvX4iIxxQNH:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/eb61ebc2aa46007d2485fe39c09feae19f783e5b/codeforlife/user/models/user.py#L194)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Because unfortunately they're not the same, since we deleted some users with our cron jobs for a few days before deciding we wanted to anonymise them instead - so we're using the TotalActivity table to keep track of the actual total figures
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`codeforlife/user/models/user.py` line 13 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/104#-Ntq_fiC-Ko_7zMgqz0w:-Ntq_fiD0Ll2bdCV1RFU:bkgk7ns) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/a3a92fd9dad6cc0039ba57a4cbc25a7a46a32fc5/codeforlife/user/models/user.py#L13)):*
> ```Python
> # pylint: disable-next=imported-auth-user
> from django.contrib.auth.models import User as _User
> from django.contrib.auth.models import UserManager
> ```

Combine imports



_Code quote:_
```Python
from django.contrib.auth.models import User as _User
from django.contrib.auth.models import UserManager
```

**Pull request merged**
