### PR TITLE
feat: otp

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12)* status: 0 of 19 files reviewed, 2 unresolved discussions

___
*[`codeforlife/user/models/session.py` line 86 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12#-NfQYsIA2JeVIpA1Orp3:-NfQYsIA2JeVIpA1Orp4:b-n10nul) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/f4768bf312d4350f303a01297dd4171dc18ecf00/codeforlife/user/models/session.py#L86)):*
> ```Python
>                 if session.is_expired:
>                     self.clear_expired(user_id)
>                     session = super().create_model_instance(data)
> ```

return 401 instead. this is a security risk which bypasses the first auth factor
___
*[`codeforlife/user/models/session.py` line 92 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12#-NfQZK1ZBgbeKZj1VAkF:-NfQZK1ZBgbeKZj1VAkG:bw2kb12) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/f4768bf312d4350f303a01297dd4171dc18ecf00/codeforlife/user/models/session.py#L92)):*
> ```Python
> 
>             except Session.DoesNotExist:
>                 session = Session.objects.get(session_key=self.session_key)
> ```

check if session.is_expired needs to be called

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12)* status: 0 of 28 files reviewed, 2 unresolved discussions

___
*[`codeforlife/user/models/backup_token.py` line 12 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12#-NfWmBvO1PcF5NcigukK:-NfWmBvO1PcF5NcigukL:blw6swe) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/e98ef041ee93534a54b8e14b44fe44655146a2fe/codeforlife/user/models/backup_token.py#L12)):*
> ```Python
> 
> 
> class BackupToken(models.Model):
> ```

rename to OtpBypassToken

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, 2 of 2 files at r3, 6 of 11 files at r4, 1 of 1 files at r5, 7 of 11 files at r6, 10 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/user/auth/backends/email_and_password.py` line 24 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12#-NfX6a53B4UXvXnMUa2K:-NfX6a53B4UXvXnMUa2L:bx31rj4) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d8a3f6963507996d862011604786b2e0c3d63d70/codeforlife/user/auth/backends/email_and_password.py#L24)):*
> ```Python
>         try:
>             user = User.objects.get(email=email)
>             if getattr(user, "is_active", True) and user.check_password(
> ```

Why remove the `is_active` check?
___
*[`codeforlife/user/auth/backends/user_id_and_login_id.py` line 25 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12#-NfX7DVnA1-uYxO1sCHn:-NfX7DVnA1-uYxO1sCHo:b-gsac8b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d8a3f6963507996d862011604786b2e0c3d63d70/codeforlife/user/auth/backends/user_id_and_login_id.py#L25)):*
> ```Python
> 
>         user = self.get_user(user_id)
>         if user and getattr(user, "is_active", True):
> ```

Same question here
___
*[`codeforlife/user/auth/backends/username_and_password_and_class_id.py` line 28 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12#-NfX7B_MCMeUCXX72nxH:-NfX7B_MCMeUCXX72nxI:b-gsac8b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/d8a3f6963507996d862011604786b2e0c3d63d70/codeforlife/user/auth/backends/username_and_password_and_class_id.py#L28)):*
> ```Python
>                 new_student__class_field__access_code=class_id,
>             )
>             if getattr(user, "is_active", True) and user.check_password(
> ```

Same question here

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
