### PR TITLE
fix: Add dependencies common to all packages

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`Pipfile` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-NydhAaiAZMzuFS92h23:-NydhAaiAZMzuFS92h24:b-u04z70) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/e57a1cf566eaf57143fe914b6544284dab0565d7/Pipfile#L14)):*
> ```TOML
> django-cors-headers = "==4.1.0"
> django-csp = "==3.7"
> django-import-export = "*"
> ```

set version number

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`Pipfile` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-NydhAaiAZMzuFS92h23:-NyeOe6gC1Hii56WokLs:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/e57a1cf566eaf57143fe914b6544284dab0565d7/Pipfile#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

set version number
</blockquote></details>

Done.

**Review by faucomte97 — COMMENTED** [review]
@SKairinos addressed feedback

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-:-NyeOfuU16rUcWDi2gbd:bwl93de)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SKairinos)

**Review by SKairinos — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`Pipfile` line 6 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-Nz3-B6SDvdu0paqhD-5:-Nz3-B6SDvdu0paqhD-6:bojvfs1) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c5066422c72c90569d34d06cc1e83e92219dcc8/Pipfile#L6)):*
> ```TOML
> name = "pypi"
> 
> [packages]
> ```

you didn't add requests

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`Pipfile` line 15 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-Nz3-endCCkqBfijSZ8i:-Nz3-endCCkqBfijSZ8j:b-lpit1r) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c5066422c72c90569d34d06cc1e83e92219dcc8/Pipfile#L15)):*
> ```TOML
> django-csp = "==3.7"
> django-import-export = "==4.0.3"
> pydantic = "==1.10.7"
> ```

pydantic is not used in the python package anywhere. can delete
___
*[`Pipfile` line 16 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-Nz3-kQI6tHeMpnqcNIN:-Nz3-kQI6tHeMpnqcNIO:b98muni) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c5066422c72c90569d34d06cc1e83e92219dcc8/Pipfile#L16)):*
> ```TOML
> django-import-export = "==4.0.3"
> pydantic = "==1.10.7"
> flask = "==2.2.3"
> ```

flask is not used in the python package anywhere. can delete

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`Pipfile` line 6 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-Nz3-B6SDvdu0paqhD-5:-NzD0u98A_Gf6i4XiJHb:b-q5ruf4) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c5066422c72c90569d34d06cc1e83e92219dcc8/Pipfile#L6)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

you didn't add requests
</blockquote></details>

cf comment in portal-react
___
*[`Pipfile` line 15 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-Nz3-endCCkqBfijSZ8i:-NzD0v_ZBdY-jEXrb0U_:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c5066422c72c90569d34d06cc1e83e92219dcc8/Pipfile#L15)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

pydantic is not used in the python package anywhere. can delete
</blockquote></details>

Done.
___
*[`Pipfile` line 16 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-Nz3-kQI6tHeMpnqcNIN:-NzD0vtIBaQuu3_KmESc:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c5066422c72c90569d34d06cc1e83e92219dcc8/Pipfile#L16)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

flask is not used in the python package anywhere. can delete
</blockquote></details>

Done.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`Pipfile` line 6 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-Nz3-B6SDvdu0paqhD-5:-NzEB7sE77vqjFdTZhFR:b-wx0nk9) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c5066422c72c90569d34d06cc1e83e92219dcc8/Pipfile#L6)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

cf comment in portal-react
</blockquote></details>

we should still add requests to our dependencies since we explicitly need it. my concern is in the future we could update to a new version of DRF that doesn't depend on requests. Therefore, we should list it as our own dependency here (which it is)

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`Pipfile` line 6 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118#-Nz3-B6SDvdu0paqhD-5:-NzEHgajEl2TiEl6OKsI:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8c5066422c72c90569d34d06cc1e83e92219dcc8/Pipfile#L6)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

we should still add requests to our dependencies since we explicitly need it. my concern is in the future we could update to a new version of DRF that doesn't depend on requests. Therefore, we should list it as our own dependency here (which it is)
</blockquote></details>

Done.

**Review by SKairinos — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
