### PR TITLE
feat: Create indy user

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/106)

### CODE REVIEW

**Review by SKairinos — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/106)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — CHANGES_REQUESTED** [review]
there's actually another issue I noticed in the PY package that we need to fix. It's important to fix for creating indy users.

in codeforlife.user.auth.password_validators.teacher, the first check needs to be:

```py
if user and user.teacher:
``` 

in codeforlife.user.auth.password_validators.student, the first check needs to be:

```py
if user and user.student and hasattr(user.student, "class_field"):
```

in codeforlife.user.auth.password_validators.independent, the first check needs to be:

```py
if user and user.student and not hasattr(user.student, "class_field"):
```

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/106#-:-NtzTXk-9c8Aw2-mcM8H:b-hoo0e4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — APPROVED** [review]
apologies, should be:

in codeforlife.user.auth.password\_validators.teacher, the first check needs to be:

```python
if user and user.teacher:
```

in codeforlife.user.auth.password\_validators.student, the first check needs to be:

```python
if user and user.student and user.student.class_field:
```

in codeforlife.user.auth.password\_validators.independent, the first check needs to be:

```python
if user and user.student and not user.student.class_field:
```

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/106#-:-NtzZcBG05EYfq-dKqp2:b-c5uy9t)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — CHANGES_REQUESTED** [review]
dummy comment to block merging

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/106#-:-NtzZoJ99uvlB_fa1ICc:bnb0vrv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by faucomte97 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/106#-:-Nu3bchVBbiCPDJ6S3ry:b-896fix)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/106)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
