### PR TITLE
fix: Clean settings

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/settings/django.py` line 64 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXOtrH-EDqXJ5oIRyo:-NvXOtrH-EDqXJ5oIRyp:bgsjc9e) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L64)):*
> ```Python
> SESSION_COOKIE_DOMAIN = "localhost" if DEBUG else "codeforlife.education"
> 
> SECURE_CONTENT_TYPE_NOSNIFF = True
> ```

add  a comment header for this group of settings and ref to the topic like the rest of the settings.

```py
# Security
# https://docs.djangoproject.com/en/3.2/topics/security/
```
___
*[`codeforlife/settings/django.py` line 68 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXPZor6PWljJcNbh57:-NvXPZor6PWljJcNbh58:b-w2tfgs) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L68)):*
> ```Python
> SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
> 
> EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
> ```

not needed. we won't be using django's email backend.
___
*[`codeforlife/settings/django.py` line 69 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXPxJgE13BJUnnxOr2:-NvXPxJgE13BJUnnxOr3:bq8rvdt) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L69)):*
> ```Python
> 
> EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
> CLOUD_STORAGE_PREFIX = "https://storage.googleapis.com/codeforlife-assets/"
> ```

What's this used for? let's discuss in a call
___
*[`codeforlife/settings/django.py` line 91 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXMZeO3ePGC1ykjRSD:-NvXMZeO3ePGC1ykjRSE:btctbmv) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L91)):*
> ```Python
> CSRF_COOKIE_NAME = f"{SERVICE_NAME}_csrftoken"
> CSRF_COOKIE_SAMESITE = "None"
> # TODO: Check if this breaks the auth system like it did on the old system
> ```

remove this TODO. This must be true. cookies should only be sent over HTTPS.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)* status: all files reviewed, 5 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/settings/django.py` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXSHv2CKoUjXmIZR4s:-NvXSHv2CKoUjXmIZR4t:b22ceju) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L21)):*
> ```Python
> # Application definition
> 
> MIDDLEWARE = [
> ```

why have we omitted  "django.middleware.security.SecurityMiddleware"?

none of the SECURE_ settings will work

https://docs.djangoproject.com/en/3.2/ref/middleware/#django.middleware.security.SecurityMiddleware

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)* status: all files reviewed, 6 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/settings/django.py` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXTUmh3x14Zkq8Mx5J:-NvXTUmh3x14Zkq8Mx5K:b-gryhwc) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L27)):*
> ```Python
>     "django.middleware.common.CommonMiddleware",
>     "django.middleware.csrf.CsrfViewMiddleware",
>     "django.contrib.messages.middleware.MessageMiddleware",
> ```

why do we need message middleware?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)* status: all files reviewed, 6 unresolved discussions (waiting on @SKairinos)

___
*[`codeforlife/settings/django.py` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXSHv2CKoUjXmIZR4s:-Nva5Mgu5REtBTopW0HH:b80k9he) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L21)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why have we omitted  "django.middleware.security.SecurityMiddleware"?

none of the SECURE_ settings will work

https://docs.djangoproject.com/en/3.2/ref/middleware/#django.middleware.security.SecurityMiddleware
</blockquote></details>

The CustomSecurityMiddleware we have in the old system actually extends the base SecurityMiddleware and ensure a specific header is set to True - so I suppose we either want to do the same in the new system?
___
*[`codeforlife/settings/django.py` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXTUmh3x14Zkq8Mx5J:-Nva5gsS8FjquIQS3NXw:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L27)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why do we need message middleware?
</blockquote></details>

Done.
___
*[`codeforlife/settings/django.py` line 64 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXOtrH-EDqXJ5oIRyo:-Nva5nvV7mc-_5DBn2d1:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L64)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

add  a comment header for this group of settings and ref to the topic like the rest of the settings.

```py
# Security
# https://docs.djangoproject.com/en/3.2/topics/security/
```
</blockquote></details>

Done.
___
*[`codeforlife/settings/django.py` line 68 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXPZor6PWljJcNbh57:-Nva5qUC1WiwOw6MlcGj:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L68)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

not needed. we won't be using django's email backend.
</blockquote></details>

Done.
___
*[`codeforlife/settings/django.py` line 69 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXPxJgE13BJUnnxOr2:-Nva5qqUBZHa2FHfJ3Ut:blpfjgs) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L69)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

What's this used for? let's discuss in a call
</blockquote></details>

Used to point to our GCP bucket for any docs we have that we need to link to on the website (ie, club packs, impact report). Also some images and videos.

https://console.cloud.google.com/storage/browser/codeforlife-assets;tab=objects?forceOnBucketsSortingFiltering=true&project=decent-digit-629&prefix=&forceOnObjectsSortingFiltering=false
___
*[`codeforlife/settings/django.py` line 91 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXMZeO3ePGC1ykjRSD:-Nva7EMS5ufK4wkA5f3z:b-qi1gn5) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L91)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove this TODO. This must be true. cookies should only be sent over HTTPS.
</blockquote></details>

No, this was part of our investigation into using sessions instead of cookies for CSRF.
If we still want to solve that issue we'll need to change it again.

https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-secure

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`.github/workflows/main.yml` line 1 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvauZGO5gaMt7SgeLkO:-NvauZGO5gaMt7SgeLkP:b-kzboqh) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/1e85deb4b415f4938adc1fa98540f033d749fcc2/.github/workflows/main.yml#L1)):*
> ```YAML
> name: Main
> ```

merge in main
___
*[`codeforlife/settings/django.py` line 69 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXPxJgE13BJUnnxOr2:-Nvav2am-1uieM6yOrlA:b-9v7wgx) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L69)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Used to point to our GCP bucket for any docs we have that we need to link to on the website (ie, club packs, impact report). Also some images and videos.

https://console.cloud.google.com/storage/browser/codeforlife-assets;tab=objects?forceOnBucketsSortingFiltering=true&project=decent-digit-629&prefix=&forceOnObjectsSortingFiltering=false
</blockquote></details>

not needed on BE. should be a FE env var
___
*[`codeforlife/settings/django.py` line 91 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXMZeO3ePGC1ykjRSD:-NvavcjZ6DgcTnc479KH:bp8vidq) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L91)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

No, this was part of our investigation into using sessions instead of cookies for CSRF.
If we still want to solve that issue we'll need to change it again.

https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-secure
</blockquote></details>

comment out and add TODO to check if needed.
and add comment CSRF_USE_SESSION=True

**Review by SKairinos — COMMENTED** [review]
add todo in auth/backends to make an admin backend

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-:-NvaxSOx9ZzAdIfDytIn:bc5zzuk)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97)

**Review by faucomte97 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-:-NvbO_2nAoEbtG3sWTbJ:b-896fix)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`.github/workflows/main.yml` line 1 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvauZGO5gaMt7SgeLkO:-NvbODnuCss1hmSr6GtL:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/1e85deb4b415f4938adc1fa98540f033d749fcc2/.github/workflows/main.yml#L1)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

merge in main
</blockquote></details>

Done.
___
*[`codeforlife/settings/django.py` line 69 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXPxJgE13BJUnnxOr2:-NvbMVJ_7U6jQT3gCZGu:bhhtivn) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L69)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

not needed on BE. should be a FE env var
</blockquote></details>

Leaving it for RR :(
___
*[`codeforlife/settings/django.py` line 76 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvbO8D41PvPfKOoJpWz:-NvbO8D41PvPfKOoJpX-:bksuce9) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L76)):*
> ```Python
> LANGUAGE_CODE = "en-gb"
> LANGUAGES = [("en-gb", _("English"))]
> TIME_ZONE = "UTC"
> ```

@SKairinos This won't break anything right?
___
*[`codeforlife/settings/django.py` line 91 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXMZeO3ePGC1ykjRSD:-NvbO0ICEHtBRd8CXRcS:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L91)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

comment out and add TODO to check if needed.
and add comment CSRF_USE_SESSION=True
</blockquote></details>

Done.

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`codeforlife/settings/django.py` line 86 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvbQh5t3toVLHR0mxRG:-NvbQh5t3toVLHR0mxRH:b94ixxu) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/359f6dd4ef9a1297380777fa48bd4cec6155112d/codeforlife/settings/django.py#L86)):*
> ```Python
> # https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
> 
> DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
> ```

@SKairinos This is what is causing the pipeline to fail - it's requiring new migrations in all apps. Thoughts?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`codeforlife/settings/django.py` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXSHv2CKoUjXmIZR4s:-Nvl4Oz49-3AQ9FE6K9e:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L21)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The CustomSecurityMiddleware we have in the old system actually extends the base SecurityMiddleware and ensure a specific header is set to True - so I suppose we either want to do the same in the new system?
</blockquote></details>

Done.
___
*[`codeforlife/settings/django.py` line 69 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvXPxJgE13BJUnnxOr2:-Nvl4RiXAVptVpmsZANd:b-bziw5x) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L69)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Leaving it for RR :(
</blockquote></details>

Removed - not needed by RR.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`codeforlife/settings/django.py` line 76 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvbO8D41PvPfKOoJpWz:-NvlsLNT42XmSng6XISP:b-3aeb0b) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/8285129b6bb9171c931c6d13cce052d7a9b53f43/codeforlife/settings/django.py#L76)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

@SKairinos This won't break anything right?
</blockquote></details>

Not sure TBH. I've never changed TZ mid-project before
___
*[`codeforlife/settings/django.py` line 86 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvbQh5t3toVLHR0mxRG:-NvlsVcD2GrzMayk3xSd:b-s6zc97) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/359f6dd4ef9a1297380777fa48bd4cec6155112d/codeforlife/settings/django.py#L86)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

@SKairinos This is what is causing the pipeline to fail - it's requiring new migrations in all apps. Thoughts?
</blockquote></details>

We can just leave to AutoField for. Probably for the best as it's more memory efficient and we currently don't need so many rows
___
*[`.github/workflows/main.yml` line 18 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108#-NvltNnQCcXb4mTYO8Cw:-NvltNnQCcXb4mTYO8Cx:bdyk6lj) ([raw file](https://github.com/ocadotechnology/codeforlife-package-python/blob/359f6dd4ef9a1297380777fa48bd4cec6155112d/.github/workflows/main.yml#L18)):*
> ```YAML
>     with:
>       # Cannot be set with an env var. Value must match in the release job.
>       python-version: 3.8
> ```

please add the following below

codecov-slug: ocadotechnology/codeforlife-package-python

**Review by SKairinos — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-python/108)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
